FROM r-base:{{{r_version}}}
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
    libssl-dev \
    libcurl4-openssl-dev \
    python-dev \
    python-flask
RUN Rscript -e 'install.packages(c("R6", "httr", "jsonlite"))'
ADD buildr ./buildr
RUN R CMD INSTALL buildr
EXPOSE 8700
ENTRYPOINT ["buildr/inst/run.py"]
